# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target ‘SDChainWallet’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
#  use_frameworks!


pod 'MJRefresh'

pod 'LBXScan/LBXNative','~> 2.2'
pod 'LBXScan/LBXZXing','~> 2.2'
pod 'LBXScan/LBXZBar','~> 2.2'
pod 'LBXScan/UI','~> 2.2'

pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SDWebImage', '~> 4.0'
pod 'IQKeyboardManager'

end
